/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GiveUpResponse {
    'explanation': string;
    'exampleSolution'?: string;
    'additionalInfo'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "explanation",
            "baseName": "explanation",
            "type": "string",
            "format": ""
        },
        {
            "name": "exampleSolution",
            "baseName": "example_solution",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additional_info",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GiveUpResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

