/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TutorialContext } from '../models/TutorialContext';
import { HttpFile } from '../http/http';

export class NewTutorialRequest {
    'context': TutorialContext;
    'concept': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "context",
            "baseName": "context",
            "type": "TutorialContext",
            "format": ""
        },
        {
            "name": "concept",
            "baseName": "concept",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NewTutorialRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

