/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CodeQuestion } from '../models/CodeQuestion';
import { HttpFile } from '../http/http';

export class UniqueCodeQuestion {
    'uuid'?: string;
    'question': CodeQuestion;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "question",
            "baseName": "question",
            "type": "CodeQuestion",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UniqueCodeQuestion.attributeTypeMap;
    }

    public constructor() {
    }
}

