/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CodeTutorial } from '../models/CodeTutorial';
import { HttpFile } from '../http/http';

export class NewCodeTutorialResponse {
    'tutorial': CodeTutorial;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tutorial",
            "baseName": "tutorial",
            "type": "CodeTutorial",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NewCodeTutorialResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

