/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReportQuestionRequest {
    'tutorialUuid': string;
    'questionUuid': string;
    'category': string;
    'details': string;
    'shouldRegenerate': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tutorialUuid",
            "baseName": "tutorial_uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "questionUuid",
            "baseName": "question_uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "shouldRegenerate",
            "baseName": "should_regenerate",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReportQuestionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

