/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TutorialContext } from '../models/TutorialContext';
import { UniqueCodeQuestion } from '../models/UniqueCodeQuestion';
import { HttpFile } from '../http/http';

export class CodeTutorial {
    'uuid'?: string;
    'context': TutorialContext;
    'questions': Array<UniqueCodeQuestion>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "TutorialContext",
            "format": ""
        },
        {
            "name": "questions",
            "baseName": "questions",
            "type": "Array<UniqueCodeQuestion>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CodeTutorial.attributeTypeMap;
    }

    public constructor() {
    }
}

